/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Jarelio Filho
 */
public class CriarPerfil extends javax.swing.JDialog {

    public String nome_cad_perfil;
    public String cpf_cad_perfil;
    public String tipo_cad_perfil;
    
    public CriarPerfil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        rbuttonJuridica = new javax.swing.JRadioButton();
        labelNome = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        cpfField = new javax.swing.JTextField();
        labelCpf = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JButton();
        rbuttonFisica = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Perfil");

        buttonGroup1.add(rbuttonJuridica);
        rbuttonJuridica.setText("Pessoa Jurídica");
        rbuttonJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuttonJuridicaActionPerformed(evt);
            }
        });

        labelNome.setText("Nome:");

        labelCpf.setText("CPF:");

        buttonCadastrar.setText("Cadastrar Perfil");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbuttonFisica);
        rbuttonFisica.setSelected(true);
        rbuttonFisica.setText("Pessoa Física");
        rbuttonFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuttonFisicaActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(buttonCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNome)
                                .addComponent(labelCpf))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbuttonFisica)
                            .addGap(18, 18, 18)
                            .addComponent(rbuttonJuridica)))
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrar)
                    .addComponent(jButton2))
                .addGap(71, 71, 71))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNome)
                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCpf)
                        .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbuttonFisica)
                        .addComponent(rbuttonJuridica))
                    .addContainerGap(122, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbuttonJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuttonJuridicaActionPerformed
        //Caso o RadioButton de CPNJ seja clicado muda a label para CPNJ:
        if(rbuttonJuridica.isSelected()){
            labelCpf.setText("CNPJ: ");
        }
    }//GEN-LAST:event_rbuttonJuridicaActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        /*Após clicar no botão cadastrar:
        É executada a função de setar as variáveis com base nos valores escolhidos na tela */
        nome_cad_perfil = nomeField.getText();
        cpf_cad_perfil = cpfField.getText();
        if(rbuttonFisica.isSelected()){
            tipo_cad_perfil = "CPF";
        }else if(rbuttonJuridica.isSelected()){
            tipo_cad_perfil = "CNPJ";
        }
        if(cpf_cad_perfil.equals("")){
            cpf_cad_perfil = "00000000000";
        }
        if(nome_cad_perfil.equals("")){
            JOptionPane.showMessageDialog(null, "Digite um nome!");
        }else{
            String mensagem = "\n" + "NOME: " + nome_cad_perfil + "\n"+ tipo_cad_perfil + ": "+ cpf_cad_perfil;
            mensagem += "\n ===================";
            mensagem += "\nOs dados estão corretos?";
                            
            int a = JOptionPane.showConfirmDialog(null, mensagem, "Perfil", 0, 1);
            if(a == 0){
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Perfil não criado");
            }
        }
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void rbuttonFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuttonFisicaActionPerformed
        //Caso o RadioButton de CPNJ seja clicado muda a label para CPF:
        if(rbuttonFisica.isSelected()){
            labelCpf.setText("CPF: ");
        }
    }//GEN-LAST:event_rbuttonFisicaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*Caso o botão voltar seja clicado:
        Seta a variável nome como uma String vazia e o cpf como um padrão 00000... e seta a escolha
        do usuário como cpf ou cpnj, fecha a tela em seguida
        */
        nome_cad_perfil = "";
        cpf_cad_perfil = "00000000000";
        if(rbuttonFisica.isSelected()){
            tipo_cad_perfil = "CPF";
        }else if(rbuttonJuridica.isSelected()){
            tipo_cad_perfil = "CNPJ";
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CriarPerfil dialog = new CriarPerfil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cpfField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelNome;
    private javax.swing.JTextField nomeField;
    private javax.swing.JRadioButton rbuttonFisica;
    private javax.swing.JRadioButton rbuttonJuridica;
    // End of variables declaration//GEN-END:variables
}
